package com.catslover.android.repositories

import android.content.res.Resources
import com.catslover.android.dataclasses.CatNames
import com.catslover.android.dataclasses.CatSounds
import com.catslover.android.dataclasses.Cat
import com.catslover.android.ilovecats.R
import javax.inject.Inject

class CatsRepository  @Inject constructor()
    : CatsSoundsInterface {
    override fun getCatSoundsList() = listOf(
        CatSounds("التغريد|الثرثرة",
            "قطه فوضع الصيد ولا تستطيع الحصول على الفريسه يحدث غالبا عندماتتفرج القطط من النوافذ و ترى فار او طائر",
            R.raw.chatteringfirst),

        CatSounds("الخرخرة|الكركرة",
            "تخرخر القطط عند الشعور بالسعادة و الاطمئنان وايضا فى اوقات المرض او الالم لتهدئه نفسها",
            R.raw.catpursecond),

        CatSounds("تمويه القطط",
            "تستخدمه القطه الانثى لتخبر الذكر انها جاهزة للتزاوج و يرد الذكر عليها بنفس الصوت ليخبرها انه تلقى الرساله",
            R.raw.caterwallingthird),

        CatSounds("الهسهسه",
            "القطه تعبر عن خوفها الشديد و تخبرنا ان تبتعد عنها و الا ستضطر للهجوم",
            R.raw.cathissfourth),

        CatSounds("زرغته القطط",
            "يصدر غالبا من القطه الانثى لصغارها كى يتتبعوهااو تصدر الصوت لمالكها لانها ترحب بيه ",
            R.raw.cattrillfifth),

        CatSounds("مواء القطط الصغيرة ",
            "يستخدمه القطط الصغيرة لجذب انظار امهاتهم عندما يكونو جائعين او بردانين",
            R.raw.babycatmeowsix),

        CatSounds("مواء القطط البالغه",
            "مواء القطط  البالغه تعنى انها تريد شيا منك اما انها جائعه او وحيدة او نحناج ان تشعر باهتمامك",
            R.raw.adultcatmeawseventh),
        CatSounds("صريخ القطط",
            "صريخ القطط يعنى انها تتشاجر مع قطط اخرى او انها خائفه للغايه او انها مريضه و تتالم",
            R.raw.catscreemeight),

        )

    override fun getCatsNamesList()= listOf(
        CatNames(0,"ساسي",R.drawable.femalebrideapp),
        CatNames(0,"تي تي",R.drawable.femalebrideapp),
        CatNames(0,"ليزي",R.drawable.femalebrideapp),
        CatNames(0,"روري",R.drawable.femalebrideapp),
        CatNames(0,"ميا",R.drawable.femalebrideapp),
        CatNames(0,"بيكي",R.drawable.femalebrideapp),
        CatNames(0,"كوين",R.drawable.femalebrideapp),
        CatNames(0,"أوني",R.drawable.femalebrideapp),
        CatNames(0,"لومي",R.drawable.femalebrideapp),
        CatNames(0,"بوسي",R.drawable.femalebrideapp),
        CatNames(0,"سكرة",R.drawable.femalebrideapp),
        CatNames(0,"جوليا",R.drawable.femalebrideapp),
        CatNames(0,"جولي",R.drawable.femalebrideapp),
        CatNames(0,"فلورا",R.drawable.femalebrideapp),
        CatNames(0,"لافي",R.drawable.femalebrideapp),
        CatNames(0,"لولو",R.drawable.femalebrideapp),
        CatNames(0,"ميشا",R.drawable.femalebrideapp),
        CatNames(0,"بوسيلي",R.drawable.femalebrideapp),
        CatNames(0,"بيتا",R.drawable.femalebrideapp),
        CatNames(0,"باربي",R.drawable.femalebrideapp),
        CatNames(0,"كاندي",R.drawable.femalebrideapp),
        CatNames(0,"بو",R.drawable.femalebrideapp),
        CatNames(0,"بيلا",R.drawable.femalebrideapp),
        CatNames(0,"كرنبة",R.drawable.femalebrideapp),
        CatNames(0,"كراملة",R.drawable.femalebrideapp),
        CatNames(0,"بسبسة",R.drawable.femalebrideapp),
        CatNames(0,"بنبونة",R.drawable.femalebrideapp),
        CatNames(0,"بسبوسة",R.drawable.femalebrideapp),
        CatNames(0,"تالا",R.drawable.femalebrideapp),
        CatNames(0,"تونة",R.drawable.femalebrideapp),
        CatNames(0,"أنوشة",R.drawable.femalebrideapp),
        CatNames(0,"فروتي",R.drawable.femalebrideapp),
        CatNames(0,"ساشا",R.drawable.femalebrideapp),
        CatNames(0,"لولي",R.drawable.femalebrideapp),
        CatNames(0,"شارميلا",R.drawable.femalebrideapp),
        CatNames(0,"لؤلؤة",R.drawable.femalebrideapp),
        CatNames(0,"لوزة",R.drawable.femalebrideapp),
        CatNames(0,"مشاكسة",R.drawable.femalebrideapp),
        CatNames(0,"بنفسج",R.drawable.femalebrideapp),
        CatNames(0,"مورايا",R.drawable.femalebrideapp),
        CatNames(0,"جيللي",R.drawable.femalebrideapp),
        CatNames(0,"سونيا",R.drawable.femalebrideapp),
        CatNames(0,"كاتي",R.drawable.femalebrideapp),
        CatNames(0,"جوجو",R.drawable.femalebrideapp),
        CatNames(0,"ديزي",R.drawable.femalebrideapp),
        CatNames(0,"دومى",R.drawable.femalebrideapp),
        CatNames(0,"دوللى",R.drawable.femalebrideapp),
        CatNames(0,"دورا",R.drawable.femalebrideapp),
        CatNames(0,"راما",R.drawable.femalebrideapp),
        CatNames(0,"بطاطس",R.drawable.femalebrideapp),
        CatNames(0,"تيتي",R.drawable.femalebrideapp),
        CatNames(0,"سمارتى",R.drawable.femalebrideapp),
        CatNames(0,"ديدي",R.drawable.femalebrideapp),
        CatNames(0,"نينا",R.drawable.femalebrideapp),
        CatNames(0,"نينى",R.drawable.femalebrideapp),
        CatNames(0,"ريرى",R.drawable.femalebrideapp),
        CatNames(0,"صوصو",R.drawable.femalebrideapp),
        CatNames(0,"فله",R.drawable.femalebrideapp),
        CatNames(0,"فيونكه",R.drawable.femalebrideapp),
        CatNames(0,"فروتا",R.drawable.femalebrideapp),
        CatNames(0,"قطقوطه",R.drawable.femalebrideapp),
        CatNames(0,"كولا",R.drawable.femalebrideapp),
        CatNames(0,"موكا",R.drawable.femalebrideapp),
        CatNames(0,"نوسا",R.drawable.femalebrideapp),
        CatNames(0,"سوسى",R.drawable.femalebrideapp),



        CatNames(1,"بوجي",R.drawable.groomcat),
        CatNames(1,"كوكو",R.drawable.groomcat),
        CatNames(1,"تيتو",R.drawable.groomcat),
        CatNames(1,"سكاي",R.drawable.groomcat),
        CatNames(1,"بيسو",R.drawable.groomcat),
        CatNames(1,"ديبو",R.drawable.groomcat),
        CatNames(1,"ماروكو",R.drawable.groomcat),
        CatNames(1,"ماكس",R.drawable.groomcat),
        CatNames(1,"جاكي",R.drawable.groomcat),
        CatNames(1,"سكار",R.drawable.groomcat),
        CatNames(1,"سيمبا",R.drawable.groomcat),
        CatNames(1,"برنس",R.drawable.groomcat),
        CatNames(1,"شوقي",R.drawable.groomcat),
        CatNames(1,"خوخ",R.drawable.groomcat),
        CatNames(1,"زعفران",R.drawable.groomcat),
        CatNames(1,"شكشك",R.drawable.groomcat),
        CatNames(1,"سمسم",R.drawable.groomcat),
        CatNames(1,"مشمش",R.drawable.groomcat),
        CatNames(1,"سيلفر",R.drawable.groomcat),
        CatNames(1,"تيمور",R.drawable.groomcat),
        CatNames(1,"زغلول",R.drawable.groomcat),
        CatNames(1,"لاكي",R.drawable.groomcat),
        CatNames(1,"لوز",R.drawable.groomcat),
        CatNames(1,"بلوتو",R.drawable.groomcat),
        CatNames(1,"رومي",R.drawable.groomcat),
        CatNames(1,"ميشو",R.drawable.groomcat),
        CatNames(1,"ميكي",R.drawable.groomcat),
        CatNames(1,"أكوا",R.drawable.groomcat),
        CatNames(1,"ركس",R.drawable.groomcat),
        CatNames(1,"بندق",R.drawable.groomcat),
        CatNames(1,"سموكي",R.drawable.groomcat),
        CatNames(1,"دنجل",R.drawable.groomcat),
        CatNames(1,"روكي",R.drawable.groomcat),
        CatNames(1,"برق",R.drawable.groomcat),
        CatNames(1,"تايجر",R.drawable.groomcat),
        CatNames(1,"شيكو",R.drawable.groomcat),
       CatNames(1,"سيزر",R.drawable.groomcat),
        CatNames(1,"اس اس",R.drawable.groomcat),
        CatNames(1,"هيرو",R.drawable.groomcat),
        CatNames(1,"سولى",R.drawable.groomcat),
        CatNames(1,"فوفو",R.drawable.groomcat),
        CatNames(1,"بطاطا",R.drawable.groomcat),
        CatNames(1,"كاسبر",R.drawable.groomcat),
        CatNames(1,"ميزو",R.drawable.groomcat),
        CatNames(1,"سينو",R.drawable.groomcat),
        CatNames(1,"بيبى",R.drawable.groomcat),


        )
}